# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 12:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('token', models.CharField(default=b'37F618A2', editable=False, max_length=8, unique=True)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student', serialize=False, to='students.StudentToken')),
                ('care_of', models.CharField(choices=[(b'Parents', b'Parents'), (b'Gardians', b'Gardians')], default=(b'Parents', b'Parents'), max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[(b'Male', b'Male'), (b'Female', b'Female'), (b'others', b'others')], default=(b'Male', b'Male'), max_length=100)),
                ('date_of_birth', models.DateField()),
                ('category', models.CharField(choices=[(b'General', b'General'), (b'SC', b'SC'), (b'ST', b'ST'), (b'Other Backward Classes', b'Other Backward Classes')], default=(b'General', b'General'), max_length=100)),
                ('occupation', models.CharField(choices=[(b'Government', b'Government'), (b'Government undertaking', b'Government undertaking'), (b'self employed', b'self employed'), (b'others', b'others')], max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('distict', models.CharField(max_length=100)),
                ('pin_code', models.IntegerField()),
                ('highest_educational_qualification', models.CharField(choices=[(b'Others', b'Others'), (b'Graduation or higher', b'Graduation or higher'), (b'Polytechnic Diploma', b'Polytechnic Diploma'), (b'Below 10th', b'Below 10th'), (b'10th Pass', b'10th Pass'), (b'12th Pass', b'12th Pass'), (b'10th + ITI', b'10th + ITI')], max_length=100)),
                ('year_of_passing', models.IntegerField()),
                ('adhar_card_number', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to=b'photos')),
                ('signature', models.ImageField(upload_to=b'signatures')),
                ('left_thumb_impression', models.ImageField(upload_to=b'thumb_impressions')),
                ('courses', models.ManyToManyField(to='students.Course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='studenttoken',
            name='by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
